site_name: CP.uz
site_url: https://cp-uz.github.io
docs_dir: src
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: blue
    accent: deep purple
extra_css:
  - stylesheets/custom.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
  - javascripts/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/contrib/auto-render.min.js

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true


nav:
  - Home: index.md
